name: bluetooth_finder
description: Find lost earbuds & Bluetooth devices
publish_to: 'none'
version: 1.2.1+6

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  flutter_blue_plus: ^1.35.2
  flutter_bluetooth_serial: ^0.4.0
  hive_flutter: ^1.1.0
  permission_handler: ^11.3.1
  purchases_flutter: ^8.1.2
  url_launcher: ^6.2.5
  package_info_plus: ^8.0.0
  just_audio: ^0.9.40
  geolocator: ^13.0.2
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  image: ^4.5.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon-foreground.png"
  adaptive_icon_monochrome: "assets/icon/icon-foreground.png"

flutter_native_splash:
  color: "#000000"
  color_dark: "#000000"
  image: "assets/icon/splash.png"
  android_12:
    color: "#000000"
    color_dark: "#000000"
    image: "assets/icon/splash.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/sounds/
